"""empty message

Revision ID: 3e9b8ffdf1d0
Revises: 0748e51bafff
Create Date: 2025-03-11 02:35:14.361782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9b8ffdf1d0'
down_revision = '0748e51bafff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
