"""empty message

Revision ID: 7adb5dd3c88f
Revises: 3dc26191fb1f
Create Date: 2025-03-11 16:28:19.608233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adb5dd3c88f'
down_revision = '3dc26191fb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.String(), nullable=True))
        batch_op.drop_column('mensagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensagem', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###
