"""empty message

Revision ID: c61ab140859a
Revises: d7ba3e6e9fed
Create Date: 2025-03-08 18:27:54.392882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61ab140859a'
down_revision = 'd7ba3e6e9fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('autor', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('conteudo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('postagens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postagens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_envio', sa.DATETIME(), nullable=True),
    sa.Column('autor', sa.VARCHAR(), nullable=True),
    sa.Column('titulo', sa.VARCHAR(), nullable=True),
    sa.Column('conteudo', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('postagem')
    # ### end Alembic commands ###
