"""empty message

Revision ID: f3d56e045d2e
Revises: e601a6e01cb5
Create Date: 2025-03-05 15:33:15.411631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d56e045d2e'
down_revision = 'e601a6e01cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sobrenome', sa.String(), nullable=True))
        batch_op.drop_column('sobrenome_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sobrenome_user', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('sobrenome')

    # ### end Alembic commands ###
